# Use official Python image
FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY . .
COPY apartments.json ./

CMD ["gunicorn", "-b", "0.0.0.0:8080", "run:app"] 